---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: ENV
  become_user: root
  shell: |
    export TEST=12
    export TYPEORM_CONNECTION=$({{ lookup('env', 'TYPEORM_CONNECTION')}})
    export TYPEORM_ENTITIES=$({{ lookup('env', 'TYPEORM_ENTITIES')}})
    export TYPEORM_HOST=$({{ lookup('env', 'TYPEORM_HOST')}})
    export TYPEORM_PORT=$({{ lookup('env', 'TYPEORM_PORT')}})
    export TYPEORM_USERNAME=$({{ lookup('env', 'TYPEORM_USERNAME')}})
    export TYPEORM_PASSWORD=$({{ lookup('env', 'TYPEORM_PASSWORD')}})
    export TYPEORM_DATABASE=$({{ lookup('env', 'TYPEORM_DATABASE')}})
    export TYPEORM_MIGRATIONS=$({{ lookup('env', 'TYPEORM_MIGRATIONS')}})
    export TYPEORM_MIGRATIONS_DIR=$({{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}})