---


  - name: "Copy backend files"
    become: yes
    synchronize:
      src: /root/project/backend
      dest: /home/ubuntu
      recursive: true

  - name: "npm install and build"
    become: true
    shell: |
      npm install
      npm run build
    args:  
        chdir: /home/ubuntu/backend
        
  - name: "Deploy code"
    become: true
    shell: |
      pm2 start -f ./main.js
    args:  
        chdir: /home/ubuntu/backend/dist
    environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"