---


  - name: "Copy backend files"
    become: yes
    synchronize:
      src: /root/project/backend
      dest: /home/ubuntu
      recursive: true

  - name: "npm install and build"
    become: true
    shell: |
      npm install
      npm run build
    args:  
        chdir: /home/ubuntu/backend
        
  - name: "Deploy code"
    become: true
    shell: |
      pm2 start -f ./main.js
    args:  
        chdir: /home/ubuntu/backend/dist
    environment:
      - ENVIRONMENT: production
      - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
      - TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
      - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
      - TYPEORM_PORT: 5432
      - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
      - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
      - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
      - TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
      - TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}" 